sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    server-->>browser: Server Responses with Status code 201 
    deactivate server
Note right of browser: The browser starts executing the JavaScript code that renders the new note in the browser